spec-version: 2
name: mazechase
region: ams

# DigitalOcean App Platform configuration for MazeChase
# Deploy: doctl apps create --spec .do/app.yaml

services:
  - name: mazechase
    github:
      repo: frank2889/mazechase
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 11300
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: PORT
        value: "11300"
      - key: DB_PATH
        value: "/app/appdata/mazechase.db"
      - key: LOG_LEVEL
        value: "info"
      - key: LOBBY_LIMIT
        value: "50"
