spec-version: 2
name: mazechase
region: ams

# DigitalOcean App Platform configuration for MazeChase
# Deploy: doctl apps create --spec .do/app.yaml

services:
  - name: mazechase
    github:
      repo: frank2889/mazechase
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: PORT
        value: "8080"
      - key: IS_DOCKER
        value: "true"
      - key: LOG_LEVEL
        value: "debug"
      - key: LOBBY_LIMIT
        value: "50"
    # Persistent storage for SQLite database
    # This ensures the database survives container restarts and deploys
    volumes:
      - name: mazechase-data
        mount_path: /appdata
        size_gb: 1
